<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->truncate();

        DB::table('books')->insert([
            [
                "id" => 1,
                "title" => "Hatter, when the.",
                "author" => "Margot Lubowitz",
                "genre" => "Accusamus",
                "description" => "Alice to find that she was dozing off, and found in it about four feet high. Whoever lives there, thought Alice, to speak to this mouse? Everything is so out-of-the-way down here, and I am sure.",
                "isbn" => "9787392061581",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2020-07-18",
                "publisher" => "Excepturi Ut"
              ],
              [
                "id" => 2,
                "title" => "I suppose it.",
                "author" => "Mayra Conroy",
                "genre" => "Aut",
                "description" => "It means much the most curious thing I ask! It is always six oclock now. A bright idea came into Alices shoulder as he said to herself That is quite enough--I hope I shant grow any more--As it.",
                "isbn" => "9797827515794",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1984-08-18",
                "publisher" => "Ut Nemo"
              ],
              [
                "id" => 3,
                "title" => "I-- Oh, do not.",
                "author" => "Tony McGlynn",
                "genre" => "Aut",
                "description" => "White Rabbit blew three blasts on the English coast you find a thing, said the Mock Turtle replied in an agony of terror. Oh, there goes his PRECIOUS nose; as an explanation. Oh, you are sure to.",
                "isbn" => "9792864279135",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2017-10-13",
                "publisher" => "Magnam Delectus"
              ],
              [
                "id" => 4,
                "title" => "I should think you.",
                "author" => "Aisha Runte",
                "genre" => "Quibusdam",
                "description" => "I suppose I ought to go with Edgar Atheling to meet William and offer him the crown. William is conduct at first was moderate. But the insolence of his tail. As if it was not very civil of you to get.",
                "isbn" => "9792912220515",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2010-01-06",
                "publisher" => "Magni Rem"
              ],
              [
                "id" => 5,
                "title" => "Alice, and she.",
                "author" => "Esta Baumbach",
                "genre" => "Quia",
                "description" => "D she added aloud.",
                "isbn" => "9791885253551",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2016-03-02",
                "publisher" => "Amet Officia"
              ],
              [
                "id" => 6,
                "title" => "Mabel, for I know.",
                "author" => "Leslie Kutch",
                "genre" => "Fugit",
                "description" => "White Rabbit returning, splendidly dressed, with a yelp of delight, and rushed at the bottom of a treacle-well--eh, stupid? But they were lying on their hands and feet at the thought that SOMEBODY.",
                "isbn" => "9793210113820",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1987-03-22",
                "publisher" => "In Qui"
              ],
              [
                "id" => 7,
                "title" => "Mock Turtle sighed.",
                "author" => "Lafayette Weber",
                "genre" => "Iste",
                "description" => "And beat him when he pleases! CHORUS. Wow! wow! wow! Here! you may SIT down, the King was the BEST butter, you know.He was an old woman--but then--always to have lessons to learn! No, I have.",
                "isbn" => "9782019496531",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1985-10-11",
                "publisher" => "Deserunt Dolores"
              ],
              [
                "id" => 8,
                "title" => "Rabbit asked. No.",
                "author" => "Patrick Wintheiser",
                "genre" => "Voluptatibus",
                "description" => "Alice herself, and once she remembered having seen in her French lesson-book. The Mouse only growled in reply. Please come back and finish ysour story! Alice called out The Queen! The Queen! and.",
                "isbn" => "9795392731755",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2002-12-28",
                "publisher" => "Laudantium Perferendis"
              ],
              [
                "id" => 9,
                "title" => "At this moment.",
                "author" => "Olen Goldner",
                "genre" => "Consequatur",
                "description" => "Rabbit came up to the three were all writing very busily on slates. What are you getting on? said the Queen, but she was saying, and the second time round, she found herself lying on their slates.",
                "isbn" => "9787214744029",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1979-06-15",
                "publisher" => "Voluptates Ipsam"
              ],
              [
                "id" => 10,
                "title" => "Alice thought she.",
                "author" => "Sigrid Blick",
                "genre" => "Omnis",
                "description" => "They all sat down at her for a long and a large one, but it had made. He took me for a conversation. Alice replied, so eagerly that the meeting adjourn, for the hot day made her next remark. Then.",
                "isbn" => "9782812983078",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1991-11-08",
                "publisher" => "Tempore Cupiditate"
              ],
              [
                "id" => 11,
                "title" => "Mock Turtle. She.",
                "author" => "Carole Cassin",
                "genre" => "Tempora",
                "description" => "Hatter began, in rather a complaining tone, and they all spoke at once, she found herself at last the Dodo suddenly called out as loud as she went on, if you only kept on good terms with him, he had.",
                "isbn" => "9789983948868",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2017-10-14",
                "publisher" => "Eum Facere"
              ],
              [
                "id" => 12,
                "title" => "I had taken the.",
                "author" => "Jayda Hayes",
                "genre" => "Tenetur",
                "description" => "Oh dear! I had nearly forgotten to ask. It turned into a graceful zigzag, and was a little house in it about four feet high. Whoever lives there, thought Alice, and, after folding his arms and.",
                "isbn" => "9791856875157",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1999-10-24",
                "publisher" => "Ut Accusamus"
              ],
              [
                "id" => 13,
                "title" => "D, she added.",
                "author" => "Horacio Jerde",
                "genre" => "Commodi",
                "description" => "Caterpillar seemed to Alice a good opportunity for croqueting one of the cupboards as she did not much like keeping so close to the door, and tried to beat time when she found she could guess, she.",
                "isbn" => "9796430055369",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2008-02-05",
                "publisher" => "Voluptates Quas"
              ],
              [
                "id" => 14,
                "title" => "Pigeon in a.",
                "author" => "Althea Johns",
                "genre" => "Ipsam",
                "description" => "YOU sing, said the Hatter: but you could keep it to speak good English); now I am opening out like the three gardeners, but she had to ask the question? said the King said to the voice of.",
                "isbn" => "9798939472920",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1977-02-01",
                "publisher" => "Voluptatem Quae"
              ],
              [
                "id" => 15,
                "title" => "Knave of Hearts.",
                "author" => "Eileen Sporer",
                "genre" => "Numquam",
                "description" => "Footman went on in these words: Yes, we went to school in the sea. The master was an old Turtle--we used to do:-- How doth the little golden key was lying under the hedge. In another minute the.",
                "isbn" => "9780017114716",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2023-09-25",
                "publisher" => "Asperiores Tempore"
              ],
              [
                "id" => 16,
                "title" => "Mock Turtle.",
                "author" => "Isabelle Klocko",
                "genre" => "Illum",
                "description" => "King added in a great interest in questions of eating and drinking. They lived on treacle, said the Eaglet. I do not believe you do either! And the moral of THAT is-- Take care of the gloves, and.", 
                "isbn" => "9781173298098",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1995-02-05",
                "publisher" => "Non Reprehenderit"
              ],
              [
                "id" => 17,
                "title" => "Mock Turtle.",
                "author" => "Lloyd Schimmel",
                "genre" => "Iusto",
                "description" => "Suddenly she came suddenly upon an open place, with a whiting. Now you know. It was, no doubt: only Alice did not like the wind, and was gone in a hoarse, feeble voice: I heard every word you.",
                "isbn" => "9795975084568",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1974-08-30",
                "publisher" => "Sunt Expedita"
              ],
              [
                "id" => 18,
                "title" => "The first witness.",
                "author" => "Chelsea Blick",
                "genre" => "Rerum",
                "description" => "Pigeon; but if they do, why then they are a kind of serpent, that is all you know why it is called a whiting? I never said I could not stand, and she tried to look about her any more questions about.",
                "isbn" => "9791363132682",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2016-05-23",
                "publisher" => "Quod Voluptatem"
              ],
              [
                "id" => 19,
                "title" => "I THINK, said.",
                "author" => "Efren Stark",
                "genre" => "Voluptas",
                "description" => "First, because I am on the look-out for serpents night and day! Why, I do so like that curious song about the same thing as a partner! cried the Gryphon. They can not have anything to put the.",
                "isbn" => "9782889118373",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1983-10-23",
                "publisher" => "Omnis Magnam"
              ],
              [
                "id" => 20,
                "title" => "I have made up my.",
                "author" => "Clementine Roberts",
                "genre" => "Necessitatibus",
                "description" => "Normans-- How are you getting on ?  said Alice, swallowing down her anger as well as she leant against a buttercup to rest her chin in salt water. Her first idea was that you never had fits, my.", 
                "isbn" => "9797713698075",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1994-06-08",
                "publisher" => "Autem Voluptatum"
              ],
              [
                "id" => 21,
                "title" => "VERY short.",
                "author" => "Seamus Greenholt",
                "genre" => "Assumenda",
                "description" => "Alice is first thought was that you never to lose YOUR temper! Hold your tongue, Ma! said the young Crab, a little bit of stick, and held it out into the book her sister sat still just as I tell.",
                "isbn" => "9785702868127",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2006-03-08",
                "publisher" => "Sed Magni"
              ],
              [
                "id" => 22,
                "title" => "These were the.",
                "author" => "Matt Breitenberg",
                "genre" => "Quis",
                "description" => "Duchess to play croquet with the Lory, with a large pigeon had flown into her face. Wake up, Dormouse! And they pinched it on both sides of the Shark, But, when the Rabbit in a very little use, as.",
                "isbn" => "9785454577575",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1976-12-09",
                "publisher" => "Minus Dolorem"
              ],
              [
                "id" => 23,
                "title" => "Duchess is knee.",
                "author" => "Pierre Doyle",
                "genre" => "Consequatur",
                "description" => "Alice; but a grin without a great hurry; and their names were Elsie, Lacie, and Tillie; and they all quarrel so dreadfully one can not hear oneself speak--and they do not give birthday presents like.",
                "isbn" => "9794473607347",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2013-04-07",
                "publisher" => "Voluptates Placeat"
              ],
              [
                "id" => 24,
                "title" => "As there seemed to.",
                "author" => "Demarcus Wiza",
                "genre" => "Et",
                "description" => "Rabbit came up to Alice, and she swam about, trying to touch her. Poor little thing! said the Cat, as soon as she went on all the unjust things-- when his eye chanced to fall a long hookah, and.",
                "isbn" => "9794226764488",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2007-07-29",
                "publisher" => "Dolores Dignissimos"
              ],
              [
                "id" => 25,
                "title" => "By this time it.",
                "author" => "Chasity Roob",
                "genre" => "Id",
                "description" => "Suppress him! Pinch him! Off with his nose, and broke off a bit of stick, and tumbled head over heels in its hurry to change the subject of conversation. Are you--are you fond--of--of dogs? The.",
                "isbn" => "9783325452457",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1979-10-18",
                "publisher" => "Eius Omnis"
              ],
              [
                "id" => 26,
                "title" => "VERY unpleasant.",
                "author" => "Dayne Konopelski",
                "genre" => "Minus",
                "description" => "Alice guessed who it was, and, as they came nearer, Alice could see it trot away quietly into the darkness as hard as he spoke. A cat may look at me like that! I could not afford to learn it.",
                "isbn" => "9785634116761",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2014-10-27",
                "publisher" => "Sequi Quos"
              ],
              [
                "id" => 27,
                "title" => "Dormouse crossed.",
                "author" => "Ethel Stehr",
                "genre" => "Dolor",
                "description" => "King, going up to them to sell, the Hatter went on, What is your name, child? My name is Alice, so please your Majesty! the soldiers had to stop and untwist it. After a while, finding that.",
                "isbn" => "9791910441533",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2002-12-10",
                "publisher" => "Voluptatibus Cupiditate"
              ],
              [
                "id" => 28,
                "title" => "Alice. Come on.",
                "author" => "Fidel Rohan",
                "genre" => "Dolores",
                "description" => "I can go back and finish your story! Alice called after her. I have something important to say! This sounded promising, certainly: Alice turned and came flying down upon her: she gave a sudden leap.",
                "isbn" => "9783118148345",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2013-03-26",
                "publisher" => "Fugiat Ducimus"
              ],
              [
                "id" => 29,
                "title" => "Alice, who always.",
                "author" => "Arvel Breitenberg",
                "genre" => "Corrupti",
                "description" => "March Hare will be When they take us up and saying, Thank you, sir, for your interesting story, but she could not remember ever having seen such a wretched height to be. It is wrong from.",
                "isbn" => "9789654873024",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1984-01-23",
                "publisher" => "Et Incidunt"
              ],
              [
                "id" => 30,
                "title" => "ONE with such.",
                "author" => "Shanelle Fay",
                "genre" => "Omnis",
                "description" => "Caterpillar took the place where it had come back and see after some executions I have ordered; and she thought at first was in confusion, getting the Dormouse said-- the Hatter went on, and most.",
                "isbn" => "9790602177279",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1996-09-04",
                "publisher" => "Est Voluptates"
              ],
              [
                "id" => 31,
                "title" => "Majesty, the.",
                "author" => "Lia Hagenes",
                "genre" => "Doloremque",
                "description" => "Hatter: but you could manage it?) And what are they made of? Alice asked in a sulky tone; Seven jogged my elbow. On which Seven looked up and walking off to other parts of the leaves: I should.",
                "isbn" => "9790258314240",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2021-05-06",
                "publisher" => "Dolorem Earum"
              ],
              [
                "id" => 32,
                "title" => "Queen added to one.",
                "author" => "Luna Berge",
                "genre" => "Qui",
                "description" => "Alice whispered, that it is done by everybody minding their own business! Ah, well! It means much the same side of WHAT? The other side of the Shark, But, when the Rabbit angrily. Here! Come and.",
                "isbn" => "9797565967015",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1989-06-04",
                "publisher" => "Voluptas Quae"
              ],
              [
                "id" => 33,
                "title" => "Alice began, in.",
                "author" => "Kirsten Murray",
                "genre" => "Eligendi",
                "description" => "Oh, I shouldn't like THAT! Oh, you foolish Alice! she answered herself. How can you learn lessons in here? Why, there is hardly room for YOU, and no one could possibly hear you. And certainly.",
                "isbn" => "9789720087393",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1982-02-01",
                "publisher" => "Facilis Id"
              ],
              [
                "id" => 34,
                "title" => "Alice, that she.",
                "author" => "Jonas Mante",
                "genre" => "Qui",
                "description" => "Just then she had hoped a fan and two or three of her favourite word moral, and the poor animal is feelings. I quite agree with you, said the Hatter. I deny it! said the King. Nearly two.",
                "isbn" => "9799838663600",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2002-12-04",
                "publisher" => "Nihil Hic"
              ],
              [
                "id" => 35,
                "title" => "Do not be all day.",
                "author" => "Orin Auer",
                "genre" => "Et",
                "description" => "However, jury-men would have this cat removed! The Queen turned angrily away from her as hard as it went, One side of WHAT? The other guests had taken his watch out of sight, he said to the.",
                "isbn" => "9785200450824",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1977-04-07",
                "publisher" => "Cupiditate Molestiae"
              ],
              [
                "id" => 36,
                "title" => "There was no One.",
                "author" => "Cayla Mann",
                "genre" => "Quia",
                "description" => "Alice glanced rather anxiously at the Queen, Really, my dear, YOU must cross-examine THIS witness. Well, if I chose, the Duchess was sitting on the Duchess is knee, while plates and dishes.",
                "isbn" => "9795596083896",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2014-08-27",
                "publisher" => "Et Voluptatem"
              ],
              [
                "id" => 37,
                "title" => "The door led right.",
                "author" => "Norwood Cassin",
                "genre" => "Id",
                "description" => "Hatter. Does YOUR watch tell you his history, As they walked off together. Alice laughed so much already, that it would make with the bread-and-butter getting so far off). Oh, my poor hands, how.",
                "isbn" => "9792228319590",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1993-09-18",
                "publisher" => "Dolor Explicabo"
              ],
              [
                "id" => 38,
                "title" => "Be off, or I will.",
                "author" => "Reilly Walsh",
                "genre" => "Voluptas",
                "description" => "Alice soon began talking again. 'Dinah will miss me very much of a good many voices all talking at once, with a little bottle on it, and talking over its head. Very uncomfortable for the White Rabbit.",
                "isbn" => "9797536992237",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2017-03-17",
                "publisher" => "Vel Blanditiis"
              ],
              [
                "id" => 39,
                "title" => "And mentioned me.",
                "author" => "Ewell Veum",
                "genre" => "Vel",
                "description" => "Alice to herself. Of the mushroom, said the King and as Alice could not remember the simple and loving heart of her skirt, upsetting all the arches are gone from this side of WHAT? The other side.",
                "isbn" => "9782045958881",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2017-10-30",
                "publisher" => "Et Eum"
              ],
              [
                "id" => 40,
                "title" => "White Rabbit read.",
                "author" => "Alda Gaylord",
                "genre" => "Ipsum",
                "description" => "They are dreadfully fond of beheading people here; the great question is, what did the archbishop find? The Mouse looked at each other for some while in silence. Alice noticed with some surprise.",
                "isbn" => "9791328836280",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2011-08-03",
                "publisher" => "Enim Autem"
              ],
              [
                "id" => 41,
                "title" => "Still she went.",
                "author" => "Jonathon Stamm",
                "genre" => "Enim",
                "description" => "The hedgehog was engaged in a sort of a well? The Dormouse again took a great hurry; and their names were Elsie, Lacie, and Tillie and they went up to the company generally, You are old, said.",
                "isbn" => "9798828602636",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2022-04-15",
                "publisher" => "Alias Iste"
              ],
              [
                "id" => 42,
                "title" => "And he got up and.",
                "author" => "Aracely Hauck",
                "genre" => "Necessitatibus",
                "description" => "No accounting for tastes! Sing her Turtle Soup, will you, will not you join the dance? Will you, will not you, will you, join the dance? You can.", 
                "isbn" => "9792693183764",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1990-03-14",
                "publisher" => "Est Pariatur"
              ],
              [
                "id" => 43,
                "title" => "Hatter asked.",
                "author" => "Kathlyn Murazik",
                "genre" => "Architecto",
                "description" => "And yet I wish you would not keep appearing and vanishing so suddenly: you make one repeat lessons! thought Alice; only, as it is asleep, I suppose you will be asleep again before it is done. Once.",
                "isbn" => "9797571443381",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1976-06-26",
                "publisher" => "Id Doloribus"
              ],
              [
                "id" => 44,
                "title" => "For some minutes.",
                "author" => "Lorena Mraz",
                "genre" => "In",
                "description" => "Alice said very politely, for I never understood what it was: at first she would feel very uneasy: to be seen: she found a little bird as soon as it could go, and making quite a large kitchen.",
                "isbn" => "9793914927761",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2019-09-24",
                "publisher" => "Atque Voluptatum"
              ],
              [
                "id" => 45,
                "title" => "I had not to bring.",
                "author" => "Stephan Ziemann",
                "genre" => "Qui",
                "description" => "Mock Turtle in a shrill, passionate voice. Would YOU like cats if you do not explain it as a partner! cried the Gryphon, and the small ones choked and had come back in their mouths; and the fall.",
                "isbn" => "9797117033014",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2013-11-24",
                "publisher" => "Laudantium Voluptatem"
              ],
              [
                "id" => 46,
                "title" => "Knave. The Knave.",
                "author" => "Lilyan Walter",
                "genre" => "Modi",
                "description" => "Queen. You make me larger, it must be kind to them, thought Alice, shall I NEVER get any older than I am now? That will be a person of authority among them, called out, First witness! The first.",
                "isbn" => "9785539784041",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2005-02-09",
                "publisher" => "Deserunt Exercitationem"
              ],
              [
                "id" => 47,
                "title" => "Eaglet. I do not.",
                "author" => "Bernhard Lakin",
                "genre" => "Incidunt",
                "description" => "The Rabbit started violently, dropped the white kid gloves in one hand and a great many more than three. Your hair wants cutting, said the Caterpillar, just as well as she came upon a little.",
                "isbn" => "9787627741622",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1986-11-28",
                "publisher" => "Dolores Sed"
              ],
              [
                "id" => 48,
                "title" => "I did: there is no.",
                "author" => "Eudora Ruecker",
                "genre" => "Sequi",
                "description" => "This did not venture to go down the chimney! Oh! So Bill is got to grow up any more if you had rather not. We indeed! cried the Gryphon, and the sounds will take care of the song. What trial is.",
                "isbn" => "9795615400741",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2020-04-26",
                "publisher" => "Explicabo Consequatur"
              ],
              [
                "id" => 49,
                "title" => "It sounded an.",
                "author" => "Audrey Donnelly",
                "genre" => "Laborum",
                "description" => "The Queen is Croquet-Ground A large rose-tree stood near the centre of the table, half hoping she might find another key on it, or at least one of the tail, and ending with the other: the only one.",
                "isbn" => "9797637560717",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1990-06-02",
                "publisher" => "Et Perferendis"
              ],
              [
                "id" => 50,
                "title" => "March Hare and the.",
                "author" => "Okey Murazik",
                "genre" => "Eos",
                "description" => "Alice, she went on all the rest, Between yourself and me. That is the first really clever thing the King put on his spectacles and looked at her, and she trembled till she too began dreaming after.",
                "isbn" => "9792099117424",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2005-01-13",
                "publisher" => "Dolorem Molestiae"
              ],
              [
                "id" => 51,
                "title" => "Queen of Hearts.",
                "author" => "Jorge Bashirian",
                "genre" => "Porro",
                "description" => "I wonder if I might venture to ask them what the next verse,' the Gryphon remarked: 'because they lessen from day to such stuff? Be off, or I'll kick you down stairs!' 'That is not said right,' said.",
                "isbn" => "9798332628580",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1987-01-08",
                "publisher" => "Aut Nemo"
              ],
              [
                "id" => 52,
                "title" => "I do not.",
                "author" => "Buck Hill",
                "genre" => "Vel",
                "description" => "The Dormouse again took a great hurry; and their names were Elsie, Lacie, and Tillie; and they lived at the end of half those long words, and, what is more, I do not want to see some meaning in it,",
                "isbn" => "9794055147766",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1990-07-22",
                "publisher" => "Minima Itaque"
              ],
              [
                "id" => 53,
                "title" => "Alice could think.",
                "author" => "Hoyt Langosh",
                "genre" => "Illo",
                "description" => "Alice, who felt ready to ask his neighbour to tell him. A nice muddle their slates will be in Bill is place for a conversation. Alice felt that she did not come the same age as herself, to see what I.",
                "isbn" => "9790833523289",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2007-07-24",
                "publisher" => "Nisi Quia"
              ],
              [
                "id" => 54,
                "title" => "The jury all wrote.",
                "author" => "Nicole Runte",
                "genre" => "Eligendi",
                "description" => "The Dormouse again took a great hurry; and their names were Elsie, Lacie, and Tillie and they walked off together. Alice was only a child! The Queen turned crimson with fury, and, after waiting.",
                "isbn" => "9788390163314",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1980-01-06",
                "publisher" => "Ipsa Quisquam"
              ],
              [
                "id" => 55,
                "title" => "OF HEARTS. Alice.",
                "author" => "Leatha Kris",
                "genre" => "Porro",
                "description" => "WHAT? The other side of the Lobster Quadrille, that she hardly knew what she did, she picked her way through the doorway and even if my head would go through, thought poor Alice, that she had.",
                "isbn" => "9789426600841",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2003-10-10",
                "publisher" => "Voluptatem Deleniti"
              ],
              [
                "id" => 56,
                "title" => "Mock Turtle to.",
                "author" => "Dayana Mann",
                "genre" => "Non",
                "description" => "Alice soon came to the part about her and to her lips. I know what they are like. I believe so, Alice replied in an impatient tone: explanations take such a dear little puppy it was! said.",
                "isbn" => "9785320724560",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2021-09-17",
                "publisher" => "Dolores Placeat"
              ],
              [
                "id" => 57,
                "title" => "Pigeon, but in a.",
                "author" => "Ruben Brakus",
                "genre" => "Tempore",
                "description" => "Alice had begun to think this a very decided tone: tell her something about the temper of your nose-- What made you so awfully clever? I have answered three questions, and that is enough, Said.",
                "isbn" => "9786564456842",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1981-09-04",
                "publisher" => "Numquam Sunt"
              ],
              [
                "id" => 58,
                "title" => "Bill, the Lizard).",
                "author" => "Shania Rice",
                "genre" => "Necessitatibus",
                "description" => "My notion was that you were not to talk about wasting IT. It is HIM. I do not believe it, said Alice, and those twelve creatures, (she was rather doubtful whether she could even make out at all.",
                "isbn" => "9792923219591",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2013-04-23",
                "publisher" => "Occaecati Fuga"
              ],
              [
                "id" => 59,
                "title" => "King said to.",
                "author" => "Moises Becker",
                "genre" => "Possimus",
                "description" => "Let me see--how IS it to be no chance of this, so that it ought to be full of soup. There is certainly too much frightened to say than his first remark, It was much pleasanter at home, thought.",
                "isbn" => "9782017808497",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2021-02-23",
                "publisher" => "Eligendi Sit"
              ],
              [
                "id" => 60,
                "title" => "March Hare, that.",
                "author" => "Nicola Gulgowski",
                "genre" => "Velit",
                "description" => "He sent them word I had not gone much farther before she gave her answer. They are done with blacking, I believe. Boots and shoes under the sea, the Gryphon went on planning to herself That is.",
                "isbn" => "9794254848273",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2003-05-13",
                "publisher" => "Quia Repudiandae"
              ],
              [
                "id" => 61,
                "title" => "Alice thought to.",
                "author" => "Dante Maggio",
                "genre" => "Est",
                "description" => "Alice replied very gravely. What else had you to offer it, said Alice, who was gently brushing away some dead leaves that lay far below her. What CAN all that green stuff be? said Alice. I have.",
                "isbn" => "9789117916596",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2003-01-14",
                "publisher" => "Rerum Provident"
              ],
              [
                "id" => 62,
                "title" => "Hatter. He will not.",
                "author" => "Aliza Gibson",
                "genre" => "Recusandae",
                "description" => "Alice, very loudly and decidedly, and the sound of many footsteps, and Alice was not an encouraging tone. Alice looked all round the rosetree for, you see, Miss, we are doing our best, afore she.",
                "isbn" => "9781823106674",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1971-09-09",
                "publisher" => "Quo Fugit"
              ],
              [
                "id" => 63,
                "title" => "Mercia and.",
                "author" => "Sedrick Kshlerin",
                "genre" => "Veniam",
                "description" => "Cat. I do not know where Dinn may be, said the Mock Turtle. And how many hours a day did you manage to do anything but sit with its head, it WOULD twist itself round and look up and throw us, with.",
                "isbn" => "9791151810716",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2005-07-29",
                "publisher" => "Optio Eveniet"
              ],
              [
                "id" => 64,
                "title" => "Dormouse into the.",
                "author" => "Luella Ondricka",
                "genre" => "Hic",
                "description" => "Alice, so please your Majesty? he asked. Begin at the place of the jury asked. That I can not take more. You mean you can not think! And oh, my poor little juror (it was exactly the right way of.",
                "isbn" => "9783414988836",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1983-09-18",
                "publisher" => "Aperiam Rerum"
              ],
              [
                "id" => 65,
                "title" => "March Hare went.",
                "author" => "Enos Renner",
                "genre" => "Tempora",
                "description" => "Mam, is this New Zealand or Australia? (and she tried to fancy what the moral of that is-- Be what you were down here till I am somebody else --but, oh dear! cried Alice, jumping up and went down.", 
                "isbn" => "9798558162837",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1990-05-26",
                "publisher" => "Ea Dolores"
              ],
              [
                "id" => 66,
                "title" => "Prizes! Alice had.",
                "author" => "Kathryne Lang",
                "genre" => "Id",
                "description" => "Queen is voice in the same thing, said the Rabbit noticed Alice, as she was exactly three inches high). But I am not particular as to size, Alice hastily replied; only one does not like changing so.",
                "isbn" => "9782089974625",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2003-03-27",
                "publisher" => "Praesentium Consequatur"
              ],
              [
                "id" => 67,
                "title" => "Who ever saw one.",
                "author" => "Cayla Adams",
                "genre" => "Hic",
                "description" => "IN the well, Alice said with a yelp of delight, and rushed at the stick, running a very interesting dance to watch, said Alice, in a low, trembling voice. There is more evidence to come down the.",
                "isbn" => "9799554899307",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1998-08-28",
                "publisher" => "Debitis Voluptas"
              ],
              [
                "id" => 68,
                "title" => "Alice. Nothing.",
                "author" => "Carole Swaniawski",
                "genre" => "Iste",
                "description" => "Alice, it would have this cat removed! The Queen had only one who had meanwhile been examining the roses. Off with their fur clinging close to her that she still held the pieces of mushroom in.",
                "isbn" => "9791967914844",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2006-08-23",
                "publisher" => "Enim Impedit"
              ],
              [
                "id" => 69,
                "title" => "Mock Turtle.",
                "author" => "Mortimer Vandervort",
                "genre" => "Similique",
                "description" => "Alice had begun to dream that she wanted much to know, but the Hatter instead! CHAPTER VII. A Mad Tea-Party There was a child, said the Hatter: I am on the bank, and of having the sentence first!'.",
                "isbn" => "9782831145655",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2017-06-11",
                "publisher" => "Velit Totam"
              ],
              [
                "id" => 70,
                "title" => "I am to see what I.",
                "author" => "Marilou Dicki",
                "genre" => "Rerum",
                "description" => "M, such as mouse-traps, and the moment she felt sure it would be a person of authority among them, called out, First witness! The first question of course had to ask any more HERE. But then",
                "isbn" => "9784256209448",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2008-10-04",
                "publisher" => "Et Et"
              ],
              [
                "id" => 71,
                "title" => "March Hare.",
                "author" => "Lavinia Kris",
                "genre" => "Aut",
                "description" => "The executioner is argument was, that if you hold it too long; and that he had taken advantage of the house, Let us both go to on the breeze that followed them, the melancholy words: --Soo--oop of.", 
                "isbn" => "9798185506820",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1974-06-07",
                "publisher" => "Et Soluta"
              ],
              [
                "id" => 72,
                "title" => "I know. Silence.",
                "author" => "Elisa Durgan",
                "genre" => "Incidunt",
                "description" => "Alice waited till the puppy is bark sounded quite faint in the direction it pointed to, without trying to box her own courage. It is no business there, at any rate, the Dormouse into the wood for.",
                "isbn" => "9781234896546",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2013-02-26",
                "publisher" => "Odit Totam"
              ],
              [
                "id" => 73,
                "title" => "Majesty means, of.",
                "author" => "Belle Lind",
                "genre" => "Est",
                "description" => "Tears Curiouser and curiouser! cried Alice in a ring, and begged the Mouse replied rather impatiently: any shrimp could have been changed for Mabel! I'll try and repeat TIS THE VOICE OF THE.", 
                "isbn" => "9783498705688",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2008-06-27",
                "publisher" => "Non Veniam"
              ],
              [
                "id" => 74,
                "title" => "I gave her one.",
                "author" => "Justina Lang",
                "genre" => "Sit",
                "description" => "Alice. Stand up and picking the daisies, when suddenly a White Rabbit was still in sight, hurrying down it. There could be no chance of this, so she set to work very diligently to write this down.",
                "isbn" => "9786477818805",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2008-02-21",
                "publisher" => "Aut Veritatis"
              ],
              [
                "id" => 75,
                "title" => "I only knew how to.",
                "author" => "Mitchell Roberts",
                "genre" => "Non",
                "description" => "King replied. Here the Queen added to one of the bottle was a very deep well. Either the well was very likely it can be, said the Hatter. You MUST remember, remarked the King, unless it was.",
                "isbn" => "9796971827036",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2002-03-14",
                "publisher" => "Rerum Adipisci"
              ],
              [
                "id" => 76,
                "title" => "I must sugar my.",
                "author" => "Katlyn Buckridge",
                "genre" => "Ipsam",
                "description" => "March Hare was said to herself, Why, they are only a pack of cards, after all. I need not be afraid of them! And who is Dinah, if I fell off the cake. * * * * * * Come, my head is free at last!.",
                "isbn" => "9786045918241",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2015-04-05",
                "publisher" => "Veniam Quibusdam"
              ],
              [
                "id" => 77,
                "title" => "The first question.",
                "author" => "Abner Stehr",
                "genre" => "Perferendis",
                "description" => "Alice noticed with some surprise that the way of speaking to it, she said to itself in a voice of the ground. So she sat down again into its eyes by this time.) You are nothing but the wise little.",
                "isbn" => "9798611751053",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1976-03-14",
                "publisher" => "Porro Minus"
              ],
              [
                "id" => 78,
                "title" => "March Hare took.",
                "author" => "Davonte DuBuque",
                "genre" => "Eveniet",
                "description" => "In another moment that it was out of their wits! So she began: O Mouse, do you want to see what I say, the Mock Turtle. Seals, turtles, salmon, and so on then, when you have cleared all the way.",
                "isbn" => "9794749343801",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2004-10-13",
                "publisher" => "Adipisci Maiores"
              ],
              [
                "id" => 79,
                "title" => "Alice sharply, for.",
                "author" => "Javon Wiza",
                "genre" => "Voluptatibus",
                "description" => "I suppose? said Alice. Come on, then, said Alice, feeling very glad she had wept when she had sat down in a minute, trying to explain it is you hate--C and D, she added aloud. Do you play.",
                "isbn" => "9795602135489",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1970-04-07",
                "publisher" => "Distinctio Rerum"
              ],
              [
                "id" => 80,
                "title" => "CHAPTER X. The.",
                "author" => "Connor Ratke",
                "genre" => "Praesentium",
                "description" => "Which shall sing? Oh, YOU sing, said the Pigeon the opportunity of showing off a bit of the house down! said the Caterpillar. Well, perhaps your feelings may be ONE. One, indeed! said the.",
                "isbn" => "9797351426962",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2000-01-16",
                "publisher" => "Repellat Omnis"
              ],
              [
                "id" => 81,
                "title" => "Duchess and the.",
                "author" => "Camila Lang",
                "genre" => "Voluptas",
                "description" => "A little bright-eyed terrier, you know, upon the other side, the puppy made another rush at Alice for some way of keeping up the fan and gloves, and, as there was a very little way out of a sea of.",
                "isbn" => "9792940864835",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1992-05-28",
                "publisher" => "Dolorum Et"
              ],
              [
                "id" => 82,
                "title" => "And certainly.",
                "author" => "Maymie Moen",
                "genre" => "Distinctio",
                "description" => "SHE, of course, the Dodo suddenly called out to her in an encouraging tone. Alice looked up, and there she saw in my time, but never ONE with such sudden violence that Alice could see, as they lay.",
                "isbn" => "9787693319107",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2020-02-22",
                "publisher" => "Repudiandae Nemo"
              ],
              [
                "id" => 83,
                "title" => "Just at this.",
                "author" => "Lamar Gutmann",
                "genre" => "Rerum",
                "description" => "I was going to happen next. The first thing she heard a little of her childhood: and how she would catch a bad cold if she could not help thinking there MUST be more to do it! Oh dear! I had nearly.",
                "isbn" => "9797235437169",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1985-11-22",
                "publisher" => "Eius Quos"
              ],
              [
                "id" => 84,
                "title" => "The Caterpillar.",
                "author" => "Angelo Cartwright",
                "genre" => "Quas",
                "description" => "THIS! (Sounds of more broken glass.) Now tell me, Pat, what is that in some book, but I shall fall right THROUGH the earth! How funny it will seem to be if you had like it very hard indeed to make.", 
                "isbn" => "9786940309595",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1981-05-10",
                "publisher" => "Nesciunt Facere"
              ],
              [
                "id" => 85,
                "title" => "This time Alice.",
                "author" => "Terrell Paucek",
                "genre" => "Aliquid",
                "description" => "She said the Mock Turtle; but it seems to be a person of authority among them, called out, Sit down, all of them were animals, and some unimportant. Alice could bear: she got up this morning.",
                "isbn" => "9787860997275",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1990-08-25",
                "publisher" => "Ipsum Delectus"
              ],
              [
                "id" => 86,
                "title" => "Mock Turtle.",
                "author" => "Eugene Collins",
                "genre" => "Reprehenderit",
                "description" => "Gryphon is, look at a king, said Alice. Well, I hardly know--No more, thank ye; I am better now but I am a deal faster than it does. Which would NOT be an old woman--but then--always to have.",
                "isbn" => "9794454563570",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1998-04-04",
                "publisher" => "Placeat A"
              ],
              [
                "id" => 87,
                "title" => "Alice said but.",
                "author" => "Patrick Beier",
                "genre" => "Et",
                "description" => "And she thought to herself. Imagine her surprise, when the race was over. However, when they liked, and left off when they had to pinch it to annoy, Because he knows it teases. CHORUS. (In which.",
                "isbn" => "9781564346018",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1984-01-16",
                "publisher" => "Qui Aut"
              ],
              [
                "id" => 88,
                "title" => "Alice to herself.",
                "author" => "Kobe Denesik",
                "genre" => "Quod",
                "description" => "I was going to remark myself. Have you seen the Mock Turtle drew a long hookah, and taking not the smallest idea how to set about it; and the small ones choked and had no idea what a Gryphon is.",
                "isbn" => "9793719926655",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1977-12-24",
                "publisher" => "Possimus Et"
              ],
              [
                "id" => 89,
                "title" => "Oh dear! I shall.",
                "author" => "Einar Barton",
                "genre" => "Vitae",
                "description" => "Alice hastily replied; at least--at least I mean what I say, the Mock Turtle sighed deeply, and drew the back of one flapper across his eyes. He looked anxiously over his shoulder as he spoke. A.",
                "isbn" => "9781122302906",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1981-04-26",
                "publisher" => "Enim Impedit"
              ],
              [
                "id" => 90,
                "title" => "Gryphon. I have.",
                "author" => "Janice Reinger",
                "genre" => "Perspiciatis",
                "description" => "NOT a serpent! said Alice desperately: he is perfectly idiotic! And she began nibbling at the corners: next the ten courtiers; these were all crowded round her, calling out in a trembling voice.",
                "isbn" => "9789077541739",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2021-03-28",
                "publisher" => "Et Non"
              ],
              [
                "id" => 91,
                "title" => "March Hare and the.",
                "author" => "Reymundo Dickinson",
                "genre" => "Temporibus",
                "description" => "I gave her one, they gave him two, You gave us three or more; They all sat down and make THEIR eyes bright and eager with many a strange tale, perhaps even with the Gryphon. I have forgotten the.",
                "isbn" => "9793489049363",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1972-11-07",
                "publisher" => "Natus Delectus"
              ],
              [
                "id" => 92,
                "title" => "I could let you.",
                "author" => "Amos Hessel",
                "genre" => "Modi",
                "description" => "Mock Turtle, they--you have seen them, of course? Yes, said Alice, quite forgetting in the house if it began ordering people about like that! said Alice hastily; but I am not used to do:-- How.",
                "isbn" => "9785929808999",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1997-04-03",
                "publisher" => "Sit Repudiandae"
              ],
              [
                "id" => 93,
                "title" => "King eagerly, and.",
                "author" => "Keaton Stroman",
                "genre" => "Odit",
                "description" => "Rabbit Sends in a hoarse growl, the world would go through, thought poor Alice, when one was not always growing larger and smaller, and being ordered about by mice and rabbits. I almost wish I.",
                "isbn" => "9798480740554",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1976-02-14",
                "publisher" => "Aut Ut"
              ],
              [
                "id" => 94,
                "title" => "Soup! Beautiful.",
                "author" => "Easton Stark",
                "genre" => "Et",
                "description" => "Queen, and she told her sister, who was sitting next to no toys to play croquet with the day and night! You see the earth takes twenty-four hours to turn into a chrysalis--you will some day, you.",
                "isbn" => "9788070647691",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2014-11-10",
                "publisher" => "Recusandae Et"
              ],
              [
                "id" => 95,
                "title" => "Alice. Why, SHE.",
                "author" => "Destiny VonRueden",
                "genre" => "Sit",
                "description" => "IS his business! said Five, in a low, weak voice. Now, I give you fair warning, shouted the Queen shrieked out. Behead that Dormouse! Turn that Dormouse out of breath, and till the Pigeon in a.",
                "isbn" => "9799365164229",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "2019-09-19",
                "publisher" => "Ut Expedita"
              ],
              [
                "id" => 96,
                "title" => "And here poor.",
                "author" => "Lonnie Strosin",
                "genre" => "Aut",
                "description" => "The March Hare went on. I do, Alice hastily replied; only one does not like changing so often, you know. I DO NOT know, said the Cat, as soon as look at it! This speech caused a remarkable.",
                "isbn" => "9787190223044",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1982-07-01",
                "publisher" => "Reiciendis Aliquid"
              ],
              [
                "id" => 97,
                "title" => "Two began in.",
                "author" => "Bonita Schoen",
                "genre" => "Sed",
                "description" => "How she longed to get through the door, she found herself safe in a tone of great surprise. Of course they were, said the Queen never left off when they liked, so that altogether, for the.",
                "isbn" => "9797710492317",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1987-09-12",
                "publisher" => "Accusamus Eos"
              ],
              [
                "id" => 98,
                "title" => "What would become.",
                "author" => "Rosanna Turner",
                "genre" => "Quasi",
                "description" => "You MUST have meant some mischief, or else you had have signed your name like an honest man. There was a little bird as soon as she could do, lying down on the top of his pocket, and pulled out a.",
                "isbn" => "9796763914579",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1978-02-28",
                "publisher" => "Non Non"
              ],
              [
                "id" => 99,
                "title" => "And then, turning.",
                "author" => "Oleta Schaden",
                "genre" => "Mollitia",
                "description" => "I can guess that, she added aloud. Do you mean by that? said the one who got any advantage from the Queen never left off quarrelling with the lobsters, out to be afraid of them! And who is.",
                "isbn" => "9781519369734",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1975-07-30",
                "publisher" => "Incidunt Excepturi"
              ],
            [
                "id" => 100,
                "title" => "March Hare said to.",
                "author" => "Logan Friesen",
                "genre" => "Ad",
                "description" => "YOUR temper Hold your tongue! added the Dormouse, and repeated her question. Why did you begin? The Hatter opened his eyes. He looked at Alice, and she could not tell whether they were lying.",
                "isbn" => "9794035166770",
                "image" => "http://placeimg.com/480/640/any",
                "published" => "1979-06-26",
                "publisher" => "Sed Debitis"
            ]] 
        );
    }
}
